config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	require 'sidekiq/web'
	require 'sidekiq-scheduler/web'
	
	resources :routes

	namespace :admin do
	  get 'dashboard', to:'dashboard#index', as: 'dashboard'
	  get 'dashboard/weekly_stats', to:'dashboard#weekly_stats', as: 'weekly_stats'
	  get 'dashboard/user_search_histories', as: 'user_search_histories'
	  get 'dashboard/user_search_stats', as: 'user_search_stats'
	  get 'dashboard/search_histories', as: 'search_histories'
	  get 'dashboard/suppliers', as: 'suppliers'
	  get 'dashboard/redirects', as: 'redirects'	
	  get 'dashboard/reviews', as: 'reviews'
	  get 'dashboard/users', as: 'users'
	  get 'dashboard/users/:id', to:'dashboard#show_user', as: 'show_user'
	  post 'dashboard/suppliers', to:'dashboard#update_supplier'
	  post 'dashboard/reviews', to: 'dashboard#update_review', as: 'update_review'
	  delete 'dashboard/reviews', to: 'dashboard#delete_review', as: 'delete_review'
	  mount Sidekiq::Web => '/sidekiq'
	end

	namespace :en do
	  get '/', to:'home#index', as: 'home'
	  get '/flights/', to: 'route#flight', as: 'flight_page'
	  get '/flight_search', to:'search_result#flight_search', as: 'flight_search'
	  get '/flights/:origin_name-:destination_name/:date', to:'search_result#search', as: 'flight_result'
	  get '/flights/:origin_name-:destination_name/:date/:id', to: 'flight_price#index', as: 'flight_prices'
	  get '/flights/:origin_name-:destination_name/', to: 'route#route', as: 'route_page'
	  get 'redirect/:origin_name-:destination_name/:date/:flight_id/:flight_price_id/:channel/:user_id', to: 'redirect#redirect', as: 'redirect'
	end
	
	get 'home/index', as: 'home'
	
	get '/flight_search', to:'search_result#flight_search', as: 'flight_search'
    
	get '/flights/', to: 'route#flight', as: 'flight_page'
	get '/flights/:origin_name-:destination_name-:month/', to: 'route#route', as: 'route_by_month_page'	
	get '/flights/:origin_name-:destination_name/', to: 'route#route', as: 'route_page'
	get '/flights/:origin_name-:destination_name/:date', to:'search_result#search', as: 'flight_result'
	get '/flights/:origin_name-:destination_name/:date/:id', to: 'flight_price#index', as: 'flight_prices'
	
	get 'redirect/:origin_name-:destination_name/:date/:flight_id/:flight_price_id/:channel', to: 'redirect#app_redirect', as: 'app_redirect'
	get 'redirect/:origin_name-:destination_name/:date/:flight_id/:flight_price_id/:channel/:user_id', to: 'redirect#redirect', as: 'redirect'

	post 'notification/price_alert_register', to: 'notification#price_alert_register', as: 'price_alert_register'
	
	get '/us', to:'static_pages#us', as: "us"
	get '/our-service', to:'static_pages#our_service', as: 'our_service'
	get '/policy', to:'static_pages#policy', as: 'policy'

	get '/airline-review/', to: 'review#airline_index', as: 'airline_review_index_page'	
	get '/airline-review/:property_name', to: 'review#airline_reviews', as: 'airline_review_page'
	get '/supplier-review/', to: 'review#supplier_index', as: 'supplier_review_index_page'	
	get '/supplier-review/:property_name', to: 'review#supplier_reviews', as: 'supplier_review_page'
	post '/review', to: 'review#register', as: 'register_review'

	get '/api/v1/city_prefetch_suggestion', to: 'api#city_prefetch_suggestion', as: 'api_city_prefetch_suggestion'
	get '/api/v1/city_suggestion/:query', to: 'api#city_suggestion', as: 'api_city_suggestion'
	get '/api/v1/service-test/', to: 'api#service_test', as: 'service_test'
	get '/api/v1/flights/', to: 'api#flights', as: 'api_flights'
	get '/api/v1/suppliers/', to: 'api#suppliers', as: 'api_suppliers'

	get '/flight-prices/:id', to: redirect('/', status: 301) #, to: 'search_result#flight_prices', as: 'flight-prices-ajax' #, :defaults => { :format => 'js' }
	get '/review/', to: redirect('/airline-review/', status: 301)
	get '/review/:property_name', to: redirect('/airline-review/%{property_name}', status: 301)


	root 'home#index'
end

app/controllers/en/flight_price_controller.rb
class En::FlightPriceController < FlightPriceController
  layout "en/layouts/application"
  
end

app/controllers/en/home_controller.rb
class En::HomeController < HomeController
  layout "en/layouts/application"
  
end

app/controllers/en/redirect_controller.rb
class En::RedirectController < RedirectController  
  layout "en/layouts/application"

end

app/controllers/en/route_controller.rb
class En::RouteController < RouteController
  layout "en/layouts/application"


end

app/controllers/en/search_result_controller.rb
class En::SearchResultController < SearchResultController
  layout "en/layouts/application"

  private
  def date_to_human date
    date = date.to_date
    if date == Date.today
      "Today"
    elsif date == (Date.today+1) 
      "Tomorrow"
    else
      date.to_date.strftime ' %-d %B' 
    end
  end
      
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    prepare_index current_user 
  end

  def prepare_index current_user
    @routes = Array.new
    routes = MostSearchRoute.new.get ENV["FIRST_PAGE_OFFERS"].to_i 
    routes.each do |route|
      begin
        route = Route.find(route[:route_id])
        @routes << {route: route, details: Route.route_detail(route)}
      rescue
      end
    end
    @is_mobile = browser.device.mobile? 
    @search_parameter = user_last_search current_user
    @user_last_searches = current_user.nil? ? nil : current_user.last_searches_without_past_dates
    @user_last_searches_limit = 3
  end

  
  def user_last_search user
    if user.nil? or user.user_search_histories.empty?
      params = default_search_params
    else 
      params = user_search_params user
    end
  end

  def user_search_params user
    origin = City.find_by(city_code: user.user_search_histories.last.route.origin)
    destination = City.find_by(city_code: user.user_search_histories.last.route.destination)
    date = user.user_search_histories.last.departure_time
    fill_params origin, destination, date
  end

  def default_search_params
    origin = City.find_by(city_code: "thr")
    destination = City.find_by(city_code: "mhd")
    date = (Date.today+1).to_s
    {origin_english_name: origin.english_name, 
    origin_code: origin.city_code,
    destination_english_name: destination.english_name, 
    destination_code: destination.city_code,
    date: date}
  end

  def fill_params origin, destination, date
    {origin_english_name: origin.english_name, 
    origin_persian_name: origin.persian_name, 
    origin_code: origin.city_code,
    destination_english_name: destination.english_name, 
    destination_persian_name: destination.persian_name, 
    destination_code: destination.city_code,
    date: date}
  end

end

app/helpers/en/flight_price_helper.rb
module En::FlightPriceHelper

  def hour_to_human_for_en_title (time)
		time_without_colon  = "#{time}".tr(':', '')
		phrase = case time_without_colon.to_i
        	when 400..1159 then "morning"
        	when 1200..1559 then "noon"
        	when 1600..1959 then "evening"
        	when 2000..2359 then "night"
        	when 0..359 then "night"
        else
        	" "
       	end
       	phrase
	end

	def english_airline_name_for airline
		if airline.nil?
		  name = ""
		else
		  name = airline.english_name.sub("-"," ").humanize
		end
		name
	end

end

app/helpers/en/home_helper.rb
module En::HomeHelper
  
  def tomorrow_price_by_dollar route
    flight = Flight.new.get_lowest_price(route,Date.today+1)
    prepare_price_message_en flight
  end

  def en_title_by_route route_id
    route = Route.find(route_id)
    origin = City.find_by(city_code: route.origin).english_name.humanize
    destination = City.find_by(city_code: route.destination).english_name.humanize
    "#{origin} to #{destination}"
  end

  def en_flight_page_path_by_route route_id, date
    route = Route.find(route_id)
    origin = City.find_by(city_code: route.origin).english_name
    destination = City.find_by(city_code: route.destination).english_name
    en_flight_result_path(origin, destination, date)
  end

  private
  def prepare_price_message_en flight
    if flight.nil?
      message = "No seat available"
    else
      message =  "$"+flight.best_price_dollar.to_s
    end
  end

end

app/helpers/en/route_helper.rb
module En::RouteHelper

  def en_dates_for_chart price_dates
    raw price_dates.map{|item| ((item[:date].to_date == Date.today)? "Today" : item[:date].to_date.strftime("%A %-d %B")) }
  end

  def en_prices_for_chart price_dates
    price_dates.map{|item| (item[:price_dollar].nil? ? 0 : item[:price_dollar])}
  end

end

app/helpers/en/search_result_helper.rb
module En::SearchResultHelper
	
	def en_delay_to_human delay
		unless delay.nil?
			return "<i class=\"warning circle yellow icon\"></i>  #{delay}m delay".html_safe
		end
	end

	def en_trip_duration_to_human total_minute
		message = " "
		unless total_minute.nil?
			message = " "
			hours = total_minute / 60
			minutes = (total_minute) % 60
			message = "#{hours} hours " unless hours == 0 
			message += "and #{minutes} minutes " unless minutes == 0 
		end
		return message
	end

	def en_stop_to_human stops
		if stops.nil?
			message = "Non-stop" 
		else
			stops = stops.split(",")
			message = "#{stops.count} stop at "
		  stops.each_with_index do |stop, index|
				message += " and " if index >= 1
				message += stop
			end
		end
		message
	end

	def number_with_zero(number)
	  number_string = number.to_s
	  case number_string.size
	  when 5
		number_with_zero = "000" + number_string
	  when 6
		number_with_zero = "00" + number_string
	  when 7
		number_with_zero = "0" + number_string
	  when 8
		number_with_zero = number_string	
	  end
	  number_with_zero
	end

	def en_day_name date,saerch_parameter_date
		date = date.to_date
		day_name = nil
		if date == Date.today 
			day_name = "today"
		elsif date == (Date.today+1) 
			day_name = "tomorrow"
		else
			day_name = date.strftime("%A")
		end
		(search_date_identifier(date,saerch_parameter_date)+day_name).html_safe
	end

	def en_price_to_human price
		if price.nil? 
			message = "<i class='plane icon'></i>".html_safe 
		else
			 message = ("$"+price.to_s ).html_safe
		end
		message
	end

	def en_hour_to_human (time)
		time_without_colon  = "#{time}".tr(':', '')
		phrase = case time_without_colon.to_i
        	when 400..1159 then "morning"
        	when 1200..1559 then "noon"
        	when 1600..1959 then "evening"
        	when 2000..2359 then "night"
        	when 0..359 then "night"
        else
        	" "
       	end
       	time + " " + phrase
	end

	def en_airplane_name_for airplane_type
	  case airplane_type.upcase
	  when "MD80","M82","MD-80","MD82","MD-82","MD83","MD-83","MD88","MD-88","MD.88","BOEING MD","MS"
	  	ariplane_name = "Boeing MD"
	  when "AB3"
	  	ariplane_name = "Airbus"
	  when "A300-600"
	  	ariplane_name= "Airbus 300"
	  when "A310","AIRBUS A310"
		  ariplane_name = "Airbus 310"
	  when "A313","AIRBUS A313"
			ariplane_name = "Airbus 313"
	  when "A319","AIRBUS A319"
			ariplane_name = "Airbus 319"
	  when "A321","AIRBUS A321", "AIRBUS 321"
			ariplane_name = "Airbus 321"
	  when "A320","AIRBUS A320","320","AIRBUS 320"
	  	ariplane_name = "Airbus 320"
	  when "BOEING 727-200","727","727-200","B727","B.727","BOEING 727"
	  	ariplane_name = "Boeing 727"
	  when "B737","737","737-500","B737-400","737-300","737-600","737-300","737-700","737-100","BOEING 737"
	  	ariplane_name = "Boeing 737"
	  when "FOKKER 100","F100", "100","FOKER"
	  	ariplane_name = "Fokker 100"
	  when "747"
	  	ariplane_name = "Boeing 747"		
	  end
	  
	  ariplane_name ||= airplane_type
	end

end

app/helpers/home_helper.rb
module HomeHelper

  def tomorrow_price_by_rial route
    flight = Flight.new.get_lowest_price(route,Date.today+1)
    prepare_price_message flight
  end

  def flight_page_path_by_route route_id, date
    route = Route.find(route_id)
    origin = City.find_by(city_code: route.origin).english_name
    destination = City.find_by(city_code: route.destination).english_name
    flight_result_path(origin, destination, date)
  end

  def persian_title_by_route route_id
    route = Route.find(route_id)
    origin = City.find_by(city_code: route.origin).persian_name
    destination = City.find_by(city_code: route.destination).persian_name
    "#{origin} به #{destination}"
  end

  private
  def prepare_price_message flight
    if flight.nil?
      message = "پر شد"
    else
      message = number_with_delimiter flight.best_price
      message +=" تومان"
    end
  end

end

app/views/en/home/index.html.erb
<% provide(:title,"PARVZHUB | Iranian flight search") %>
<% provide(:description,"All Iranian domestic flights from the best Iranian online travel agencies in on place") %>

<header>


<div class="ui grid" id="header">
  		<div class="two column row">
			<div class="right floated left aligned column">
				<a class="header-language" href="<%= home_path %>">
					فارسی
				</a>
    		</div>
    		<div class="left floated right aligned column">
    			<%#= render 'devise/menu/login_items' %>
    			<%#= render 'devise/menu/registration_items' %>
       		</div>
  		</div>
	</div>
</header>

<div class="ui vertical masthead segment" id="cover-photo" style="direction: rtl; margin-bottom: 2em;">  
	<div class="ui container text center aligned header" id="slogan">
		<a href="/">
    		<div class="item" id="slogan-text">
      			<!--<i class="circle notched icon" style="color: white"></i>-->
      			<span id="company-name">PARVAZHUB</span>
    		</div>
		  </a>

		<h1 class="ui header inverted center aligned web-font" style="line-height: 2em;font-size: 1.28rem !important;">
			<span id="slogan-description">	
				Search & compare
				<b class="yellow">  Iran </b> 
				domestic flights 
			</span>	
		</h1>
	</div>

	<div class="ui stackable one column grid centered" style="margin-top: 1em">
   		<%= form_for(:search, url: en_flight_search_path, method: :get, html: {id:"flight_search"}) do |f| %>
    		<div class="ui huge form en" >
     			<div class="two fields" style="margin-left:12px">
					<div class="field input-container">
						<label class="search-label">From</label>
						<%= f.text_field :originـfield,{:class =>'origin-field typeahead web-font en',placeholder: "origin, type city name", :value => @search_parameter[:origin_english_name]} %>						   
						<%= f.hidden_field :origin,{:id =>'origin',:value => @search_parameter[:origin_english_name]} %>
					</div> 
					<div class="field input-container">
					  <label class="search-label">To</label>
					  <%= f.text_field :destination_field,{:class =>'destination-field typeahead web-font',placeholder: "destination, type city name", :value => @search_parameter[:destination_english_name]} %>
					  <%= f.hidden_field :destination,{:id =>'destination',:value => @search_parameter[:destination_english_name]} %>
      				</div> 
  				</div>
  				<div id="date-picker" style="height: 10em; font-family: samim;">
						<%= f.text_field :date, {id: 'date-picker-field', value: @search_parameter[:date]} %>
      			</div>
  				<div class="ui center aligned basic segment" style="margin-top: 50px;">
  					<button class="ui submit massive yellow web-font fluid left labeled waiting-modal icon button" type="submit">
							Search Flights
					</button>
  				</div>
			</div>
		<%end%>
	</div>
	
	<div>
		<h4 class="home-calendar-title">
		<i class="checked calendar icon"></i>
			Don't decided on dates yet? check prices on calendar<br><br>
			<%= link_to "Tehran to Shiraz", en_route_page_path(origin_name:  "tehran",destination_name: "shiraz"),class:"city-page-link" %> | 
			<%= link_to "Tehran to Yazd", en_route_page_path(origin_name:  "tehran",destination_name: "yazd"),class:"city-page-link" %> | 
			<%= link_to "Tehran to Isfahan", en_route_page_path(origin_name:  "tehran",destination_name: "isfahan"),class:"city-page-link" %>	
		</h4>
	</div>
	
</div>

<% unless @user_last_searches.nil? %>
	<div class="ui horizontal divider">
	Recent searches
	</div>
	<div class="ui three stackable cards en" style="width:70%;margin:auto">
		<% @user_last_searches.each do |user_last_search| %>
			<div class="card">
				<div class="content">
					<div class="header web-font text-left" style="color: #7b7777">
						<i class=" plane icon"></i>
						<%= en_title_by_route user_last_search[:route_id] %>
					</div>
					<% user_last_search[:dates].each_with_index do |date, index| %>
						<% if index < @user_last_searches_limit %>
							<div class="description text-center en" style="padding-top: 4px">
								<a  href="<%= en_flight_page_path_by_route user_last_search[:route_id], date  %>">
									<%= date.to_date.strftime "%A %-d %B"   %>
									<i class="left arrow icon"></i>
								</a>	
							</div>
						<% end %> 	
					<% end %>   
				</div>
			</div>
		<% end %>   
	</div>
<% end %>

<div class="ui horizontal divider">
	iran popular destinations
</div>

<div class="ui three stackable cards" style="width:70%;margin:auto;">
	<% @routes.each do |route| %>
		<div class="card">
			<div class="content">
				<div class="header web-font text-center">
					<a  href="<%= en_flight_result_path(route[:details][:origin][:english_name], route[:details][:destination][:english_name], "tomorrow") %>">
						<%= route[:details][:origin][:english_name].humanize %>
							to
						<%= route[:details][:destination][:english_name].humanize %>
					</a>
				</div>
				<div class="description text-center dir-rtl">
					<a  href="<%= en_flight_result_path(route[:details][:origin][:english_name], route[:details][:destination][:english_name], "tomorrow") %>">
						<%= tomorrow_price_by_dollar route[:route] %>	
					</a>	
				</div>
			</div>
			<a style="color:white" href="<%= en_flight_result_path(route[:details][:origin][:english_name], route[:details][:destination][:english_name], "tomorrow") %>">
				<div class="ui bottom attached button yellow web-font dir-rtl">
					<i class="left arrow icon"></i>	
					tomorrow flights			
				</div>
			</a>
		</div>
	<% end %>   
</div>

<%= render 'en/layouts/searchbox-helper', date_picker_inline: true %>   
<%= render 'en/layouts/footer' %>