config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	require 'sidekiq/web'
	require 'sidekiq-scheduler/web'
	
	resources :routes

	namespace :admin do
	  get 'dashboard', to:'dashboard#index', as: 'dashboard'
	  get 'dashboard/weekly_stats', to:'dashboard#weekly_stats', as: 'weekly_stats'
	  get 'dashboard/user_search_histories', as: 'user_search_histories'
	  get 'dashboard/user_search_stats', as: 'user_search_stats'
	  get 'dashboard/search_histories', as: 'search_histories'
	  get 'dashboard/suppliers', as: 'suppliers'
	  get 'dashboard/redirects', as: 'redirects'	
	  get 'dashboard/reviews', as: 'reviews'
	  get 'dashboard/users', as: 'users'
	  get 'dashboard/users/:id', to:'dashboard#show_user', as: 'show_user'
	  post 'dashboard/suppliers', to:'dashboard#update_supplier'
	  post 'dashboard/reviews', to: 'dashboard#update_review', as: 'update_review'
	  delete 'dashboard/reviews', to: 'dashboard#delete_review', as: 'delete_review'
	  mount Sidekiq::Web => '/sidekiq'
	end

	namespace :en do
	  get '/', to:'home#index', as: 'home'
	  get '/flights/', to: 'route#flight', as: 'flight_page'
	  get '/flight_search', to:'search_result#flight_search', as: 'flight_search'
	  get '/flights/:origin_name-:destination_name/:date', to:'search_result#search', as: 'flight_result'
	  get '/flights/:origin_name-:destination_name/:date/:id', to: 'flight_price#index', as: 'flight_prices'
	  get '/flights/:origin_name-:destination_name/', to: 'route#route', as: 'route_page'
	  get 'redirect/:origin_name-:destination_name/:date/:flight_id/:flight_price_id/:channel/:user_id', to: 'redirect#redirect', as: 'redirect'
	end
	
	get 'home/index', as: 'home'
	
	get '/flight_search', to:'search_result#flight_search', as: 'flight_search'
    
	get '/flights/', to: 'route#flight', as: 'flight_page'
	get '/flights/:origin_name-:destination_name-:month/', to: 'route#route', as: 'route_by_month_page'	
	get '/flights/:origin_name-:destination_name/', to: 'route#route', as: 'route_page'
	get '/flights/:origin_name-:destination_name/:date', to:'search_result#search', as: 'flight_result'
	get '/flights/:origin_name-:destination_name/:date/:id', to: 'flight_price#index', as: 'flight_prices'
	
	get 'redirect/:origin_name-:destination_name/:date/:flight_id/:flight_price_id/:channel', to: 'redirect#app_redirect', as: 'app_redirect'
	get 'redirect/:origin_name-:destination_name/:date/:flight_id/:flight_price_id/:channel/:user_id', to: 'redirect#redirect', as: 'redirect'

	post 'notification/price_alert_register', to: 'notification#price_alert_register', as: 'price_alert_register'
	
	get '/us', to:'static_pages#us', as: "us"
	get '/our-service', to:'static_pages#our_service', as: 'our_service'
	get '/policy', to:'static_pages#policy', as: 'policy'

	get '/airline-review/', to: 'review#airline_index', as: 'airline_review_index_page'	
	get '/airline-review/:property_name', to: 'review#airline_reviews', as: 'airline_review_page'
	get '/supplier-review/', to: 'review#supplier_index', as: 'supplier_review_index_page'	
	get '/supplier-review/:property_name', to: 'review#supplier_reviews', as: 'supplier_review_page'
	post '/review', to: 'review#register', as: 'register_review'

	get '/api/v1/city_prefetch_suggestion', to: 'api#city_prefetch_suggestion', as: 'api_city_prefetch_suggestion'
	get '/api/v1/city_suggestion/:query', to: 'api#city_suggestion', as: 'api_city_suggestion'
	get '/api/v1/service-test/', to: 'api#service_test', as: 'service_test'
	get '/api/v1/flights/', to: 'api#flights', as: 'api_flights'
	get '/api/v1/suppliers/', to: 'api#suppliers', as: 'api_suppliers'

	get '/flight-prices/:id', to: redirect('/', status: 301) #, to: 'search_result#flight_prices', as: 'flight-prices-ajax' #, :defaults => { :format => 'js' }
	get '/review/', to: redirect('/airline-review/', status: 301)
	get '/review/:property_name', to: redirect('/airline-review/%{property_name}', status: 301)


	root 'home#index'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin

  def user_search_histories
  	@ush = UserSearchHistory.includes(:route).order(id: :desc).first(500)
  end

  def search_histories
  	@sh = SearchHistory.includes(:route).order(id: :desc).first(300)
  end

  def suppliers
  	@supplier_list = Supplier.all
  end

  def update_supplier
  	id = params[:id]
  	status = params[:status]
  	supplier = Supplier.find(id)
  	supplier[:status] = status
  	supplier.save
  	@supplier_list = Supplier.all
  	render :suppliers
  end

  def reviews
    @reviews = Review.all
  end

  def show_user
    @user = User.find(params[:id])
  end

  def index
    @channels = ["website","telegram","android","ionic"]
  end

  def weekly_stats
    @channels = ["website","telegram","android","ionic"]
    @show_search_history = false
  end

  def users
    @channel = params[:channel]
    if @channel.nil?
      @users = User.left_joins(:user_search_histories).group(:id).order('COUNT(user_search_histories.id) DESC').limit(1000)
    else
      @users = User.where(channel: @channel).left_joins(:user_search_histories).group(:id).order('COUNT(user_search_histories.id) DESC').limit(1000)
    end
  end
      
  def redirects
    today_redirects =  calculate_redirects(Date.today, Date.today+1)
    all_redirects =  calculate_redirects(Date.today-365, Date.today+1)
    this_week_redirects =  calculate_redirects(Date.today-7, Date.today+1)
    week_before_redirects =  calculate_redirects(Date.today-14, Date.today-7)
    week_before_that_redirects =  calculate_redirects(Date.today-21, Date.today-14)
    this_month_redirects = calculate_redirects((Date.today-(Date.today.to_date.to_parsi.strftime("%-d")).to_i), Date.today+1)
    @results = {this_month: this_month_redirects, today:today_redirects,all:all_redirects,this_week:this_week_redirects,week_before:week_before_redirects,week_before_that:week_before_that_redirects} 
  end

  def calculate_redirects(begin_date,end_date)
    supplier = Hash.new
    Redirect.where('created_at > ? and created_at <?',begin_date,end_date).each do |redirect|
      supplier[redirect.supplier.to_sym] = 0 if supplier[redirect.supplier.to_sym].nil?
      supplier[redirect.supplier.to_sym] += 1
    end
    supplier = Hash[ supplier.sort_by { |key, val| key } ]  
  end

  def user_search_stats
    user_search_histories = UserSearchHistory.where("created_at >?","2017-09-11")

    @user_search_histories_all = user_search_histories.count
    
    routes_count = user_search_histories.group(:route_id).order('count_id desc').count('id')
    @routes_count_hash = Hash.new
    routes_count.each do |route|
      route_id = route[0]
      route_codes = Route.find(route_id)
      hash_key = route_codes.origin+"-"+route_codes.destination
      @routes_count_hash[hash_key.to_sym] = route[1]
    end

    @dates_count = Hash.new
    user_search_histories.each do |user_search_history|
      
      begin 
        hash_key = (user_search_history.departure_time.to_date - user_search_history.created_at.to_date).to_i
      rescue
        next
      end

      if @dates_count[hash_key] 
        @dates_count[hash_key] +=1
      else
        @dates_count[hash_key] = 1
      end
    end
    @dates_count = Hash[@dates_count.sort_by{|k, v| v}.reverse]
  end

  def update_review
    review = Review.find(review_params[:id])
    review.update(review_params)
    #review.save
  end

  def delete_review
    review = Review.find(review_params[:id])
    review.destroy
  end

  private

  def review_params
    params.require(:review).permit(:id, :published)
  end
  
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
	def tehran_time date
		date - ENV["IRAN_ADDITIONAL_TIMEZONE"].to_f.minutes
	end

	def user_search_history(date, channel=nil)
		if channel.nil?
			user_search = UserSearchHistory.where("created_at > ? and created_at < ?", tehran_time(date), tehran_time(date+1))
		else
			user_search = UserSearchHistory.where("created_at > ? and created_at < ?", tehran_time(date), tehran_time(date+1)).where(channel: channel)
		end				
		user_search.count	
	end

	def user_search_history_all(channel=nil)
		if channel.nil?
			user_search = UserSearchHistory.count
		else
			user_search = UserSearchHistory.where(channel: channel).count
		end			
	end

	def user_flight_price_history(date, channel=nil)
		if channel.nil?
			user_flight_price = UserFlightPriceHistory.where("created_at > ? and created_at < ?", tehran_time(date), tehran_time(date+1)).count
		else
			user_flight_price = UserFlightPriceHistory.where("created_at > ? and created_at < ?", tehran_time(date), tehran_time(date+1)).where(channel: channel).count
		end		
	end

	def user_flight_price_history_all(channel=nil)
		if channel.nil?
			user_flight_price = UserFlightPriceHistory.count
		else
			user_flight_price = UserFlightPriceHistory.where(channel: channel).count
		end			
	end

	def redirect(date, channel=nil)
		count = 0
		application = ApplicationController.new
		if channel.nil?
			redirects = Redirect.where("created_at > ? and created_at < ?", tehran_time(date), tehran_time(date+1))
		else
			redirects = Redirect.where("created_at > ? and created_at < ?", tehran_time(date), tehran_time(date+1)).where(channel: channel)
		end	
		redirects.each do |redirect|
			count +=1 unless application.is_bot(redirect.user_agent)
		end
		return count
	end

	def redirect_all(channel=nil)
	  if channel.nil?
		redirect = Redirect.all.count
	  else
		redirect = Redirect.where(channel: channel).count
	  end
	end

	def notification date
      notification = Notification.where("created_at > ? and created_at < ?", tehran_time(date), tehran_time(date+1))
	  notification.count
	end

	def notification_all
      notification = Notification.all
	  notification.count
	end

	def search_history date
      search_history = SearchHistory.where("created_at > ? and created_at < ?", tehran_time(date), tehran_time(date+1))
	  search_history.count
	end

	def search_history_all
      search_history = SearchHistory.all
	  search_history.count
	end

	def user date
		User.where("created_at > ?", tehran_time(date)).count
	end

	def review date
		Review.where("created_at > ?", tehran_time(date)).count
	end
	
end

app/views/admin/dashboard/_menu.html.erb
<div class="ui teal inverted stackable menu web-font" style="margin-top: 0 !important;direction: rtl;">
    <a class="item <%= 'active' if params[:action] == 'index' %>" href="<%= admin_dashboard_path %>">
    خانه
  </a>
  <a class="item <%= 'active' if params[:action] == 'weekly_stats' %>" href="<%= admin_weekly_stats_path %>">
    آمار هفتگی
  </a>
  <a class="item <%= 'active' if params[:action] == 'users' %>" href="<%= admin_users_path %>">
    کاربران
  </a>
  <a class="item <%= 'active' if params[:action] == 'redirects' %>" href="<%= admin_redirects_path %>">
    ریدایرکت‌ها
  </a>
  <a class="item <%= 'active' if params[:action] == 'reviews' %>" href="<%= admin_reviews_path %>">
    ریویوها
  </a>
  <a class="item <%= 'active' if params[:action] == 'search_histories' %>" href="<%= admin_search_histories_path %>">
    سرچ‌هیستوری
  </a>
  <a class="item <%= 'active' if params[:action] == 'suppliers' %>" href="<%= admin_suppliers_path %>">
    ساپلایرها
  </a>
  <a class="item <%= 'active' if params[:action] == 'user_search_histories' %>" href="<%= admin_user_search_histories_path %>">
    یوزرسرچ‌هیستوری
  </a>
  <a class="item <%= 'active' if params[:action] == 'user_search_stats' %>" href="<%= admin_user_search_stats_path %>">
    آمار سرچ
  </a>
  
</div>

app/views/admin/dashboard/index.html.erb
<% provide(:title,"خانه") %>
<%= render 'menu' %>

<div class="ui container" style="margin-top: 2em">

	<h4 class="ui horizontal divider header">
		Today
	</h4>
	<div class="ui statistics">
		<div class="orange statistic">
			<div class="value">
				<%= user_search_history(Date.today)  %>
			</div>
			<div class="label">
				Search 
			</div>
		</div>
		<div class="orange statistic">
			<div class="value">
				<%= user_flight_price_history(Date.today) %>
			</div>
			<div class="label">
				Supplier
			</div>
		</div>
		<div class="orange statistic">
			<div class="value">
				<%= redirect(Date.today) %>
			</div>
			<div class="label">
				Redirect
			</div>
		</div>
		<div class="orange statistic">
			<div class="value">
				<%= user(Date.today) %>
			</div>
			<div class="label">
				User
			</div>
		</div>
		<div class="orange statistic">
			<div class="value">
				<%= review(Date.today) %>
			</div>
			<div class="label">
				Reviews
			</div>
		</div>
	</div>

</div>

app/views/admin/dashboard/redirects.html.erb
<% provide(:title,"ریدایرکت") %>
<%= render 'menu' %>

<div class="ui container" style="margin-top: 2em">
  

<% @results.each do |name,period| %>
  	<div class="row" style="padding: 1em">
  		<div class="ui label">
          <%= name.to_s %>
		</div>
	</div>
	<div class="row" style="direction: rtl">
		<div class="ui small ten statistics" >
  			<% period.each do |supplier,count| %>
	  			<div class=" green statistic" >
		  			<div class="value ">
	  					<%= count %>
	  				</div>
		  			<div class="label web-font">
	  					<%= supplier  %>
	  				</div>
	  			</div>
  			<% end %>
  		</div>
  	</div>
    <div class="ui divider"></div>
      
 <% end %> 	


</div>

app/views/admin/dashboard/reviews.html.erb
<% provide(:title,"ریویوها") %>
<%= render 'menu' %>

<div class="ui container" style="margin-top: 2em">

	<h4 class="ui horizontal divider header">
	Reviews
	</h4>
	<div class="ui statistics">
		<div class=" statistic">
			<div class="value">
				<%= Review.count %>
			</div>
			<div class="label">
				Total review
			</div>
		</div>
		<div class="yellow statistic">
			<div class="value">
				<%= Review.where("created_at > ?", Date.today).count %>
			</div>
			<div class="label">
				Today review
			</div>
		</div>
	</div>
	
	<h4 class="ui horizontal divider header">
	Details
	</h4>

	<table class="ui celled striped table ">
		
		<tbody>
			<% @reviews.each do |review|  %>
			<tr class="center aligned">
				<td><%= review.id %></td>
				<td>
					<% if review.user_id.nil? %>
						<%= review.author %>
					<% else %>
						<a href="<%= admin_show_user_path(id: review.user_id) %>">
							<%= review.author %>
						</a>
					<% end %>
				</td>
				<td><%= review.page %></td>
				<td><%= review.text %></td>
				<td><%= review.rate %></td>
				<td><%= time_ago_in_words(review.created_at) %></td>
				<td>
					<%= form_for(:review, url: admin_update_review_path, method: :post, html: {id:"review_form"}) do |f| %>
						<%= f.hidden_field :id, {:value => review.id} %>
						<% if review.published? %>
							<%= f.hidden_field :published,{ :value => false} %>	
							<div class="ui small basic icon buttons">
  								<button type="submit" value="review[submit]" class="ui button"><i class="toggle on icon"></i></button>
							</div>
						<% else %>
							<%= f.hidden_field :published,{ :value => true} %>	
							<div class="ui small basic icon buttons">
  								<button type="submit" value="review[submit]" class="ui button"><i class="toggle off icon"></i></button>
							</div>
						<% end %>					   
					<%end%>
					<%= form_for(:review, url: admin_update_review_path, method: :delete, html: {id:"review_form"}) do |f| %>
						<%= f.hidden_field :id, {:value => review.id} %>
						<div class="ui small basic icon buttons">
  							<button type="submit" value="review[submit]" class="ui button"><i class="trash alternate icon"></i></button>
						</div>
					<% end %>					   
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/admin/dashboard/search_histories.html.erb
<% provide(:title,"Search history") %>
<%= render 'menu' %>

<div class="ui container" style="margin-top: 2em">
	<table class="ui celled striped table ">
		<thead>
			<tr class="center aligned">
				<th><h4>route</h4></th>
				<th><h4>Departure Time</h4></th>
				<th><h4>status</h4></th>
				<th><h4>supplier</h4></th>
				<th><h4>successful</h4></th>
				<th><h4>created at</h4></th>
			</tr>
		</thead>
		<tbody>
			<% @sh.each do |item|  %>
			<tr class="center aligned">
				<td><%= item.route.origin + " - " + item.route.destination %></td>
				<td><%= item.departure_time %></td>
				<td>
					<% if item.successful %>
						<span class="ui teal label"><%= item.status %></span>
					<% else %>
						<span class="ui orange label"><%= item.status %></span>
					<% end %>
					<span style="color:gray">
						<%= (item.updated_at - item.created_at).round.to_s + "s" %>
					</span>
				</td>
				<td><%= item.supplier_name %></td>
				<td><%= item.successful %></td>
				<td><%= time_ago_in_words(item.created_at) %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/admin/dashboard/show_user.html.erb
<% provide(:title, @user.id.to_s) %>
<%= render 'menu' %>

<div class="ui container" style="margin-top: 2em">
    <h4 class="ui horizontal divider header">
        User Info
    </h4>
    <%= @user.email%> |  <%= @user.first_name %> <%= @user.last_name%>


    <h4 class="ui horizontal divider header">
        Total
    </h4>
    <div class="ui statistics">
		<div class="orange statistic">
			<div class="value">
				<%= @user.user_search_histories.count  %>
			</div>
			<div class="label">
                Searches 
			</div>
        </div>
        <div class="orange statistic">
			<div class="value">
				<%= @user.user_flight_price_histories.count  %>
			</div>
			<div class="label">
				Suppliers 
			</div>
        </div>
        <div class="orange statistic">
			<div class="value">
				<%= @user.redirects.count  %>
			</div>
			<div class="label">
				Redirects 
			</div>
        </div>
    </div>

    <h4 class="ui horizontal divider header">
		Reviews
    </h4>
    <div class="ui relaxed divided list">
        <% @user.reviews.each do |review| %>
            <div class="item">
                <i class="large comment middle aligned icon"></i>
                <div class="content">
                    <span class="header">
                        <%= review.page  %>  
                        <%= review.rate  %>  
                    </span>
                    <div class="description">
                        <%= review.text  %> | 
                        <%= review.created_at  %>
                    </div>    
                </div>
            </div>
        <% end %>
    </div>
    
    
    <h4 class="ui horizontal divider header">
		Searches
    </h4>
    <div class="ui relaxed divided list">
        <% @user.user_search_histories.includes(:route).each do |search| %>
            <div class="item">
                <i class="large plane middle aligned icon"></i>
                <div class="content">
                    <span class="header">
                        <%= search.route.origin  %>
                        <%= search.route.destination  %>    
                    </span>
                    <div class="description">
                        <%= search.departure_time  %>  |
                        <%= search.channel  %>    |
                        <%= time_ago_in_words search.created_at  %> 
                    </div>
                </div>
            </div>
        <% end %>
    </div>

    <h4 class="ui horizontal divider header">
		Supplier Page
    </h4>
    <div class="ui relaxed divided list">
        <% @user.user_flight_price_histories.each do |search| %>
            <% flight = Flight.find(search.flight_id)  %>
            <div class="item">
                <i class="large plane middle aligned icon"></i>
                <div class="content">
                    <span class="header">
                        <%  airline = Airline.find_by(code: flight.airline_code) %>
                        <%= airline.nil? ? flight.airline_code : airline.english_name %> |
                        <%= flight.flight_number %>
                        </span>
                    <div class="description">
                        <%= flight.airplane_type %> |
                        <%= flight.price_by %> |
                        <%= flight.best_price %> |
                        <%= search.channel  %>    |
                        <%= time_ago_in_words search.created_at  %>    
                    </div>
                </div>
            </div>
        <% end %>
    </div>

    <h4 class="ui horizontal divider header">
		Redirects 
    </h4>
    <div class="ui relaxed divided list">
        <% @user.redirects.each do |redirect| %>
            <div class="item">
                <i class="large plane middle aligned icon"></i>
                <div class="content">
                    <span class="header">
                        <%= redirect.flight_id  %>
                        <%= redirect.supplier  %>    
                    </span>
                    <div class="description">
                        <%= redirect.user_agent  %>   |
                        <%= redirect.channel  %>    |
                        <%= time_ago_in_words redirect.created_at  %>    
                    </div>
                </div>
            </div>
        <% end %>
    </div>
	

</div>

app/views/admin/dashboard/suppliers.html.erb
<% provide(:title,"ساپلایرها") %>
<%= render 'menu' %>

<div class="ui container" style="margin-top: 2em">
	<table class="ui celled striped table ">
		<tbody>
			<% @supplier_list.each do |item|  %>
				<tr class="center aligned">
					<%= form_tag(admin_dashboard_suppliers_path, method: :post, class:"ui form") do %>
					<%= hidden_field_tag(:id, item.id) %>

						<td><%= item.id %></td>
						<td><%= item.name %></td>
						<td>
							<%= select_tag(:status, options_for_select([['active', true], ['deactive', false]], item.status), {class:"ui  dropdown"}) %>
						</td>
						<td><%= submit_tag("submit", {class:"ui teal button"}) %></td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/admin/dashboard/user_search_histories.html.erb
<% provide(:title,"User Search history") %>
<%= render 'menu' %>

<div class="ui container" style="margin-top: 2em">
	<table class="ui celled striped table ">
		<thead>
			<tr class="center aligned">
				<th><h4>id</h4></th>
				<th><h4>route</h4></th>
				<th><h4>Departure Time</h4></th>
				<th><h4>created at</h4></th>
			</tr>
		</thead>
		<tbody>
			<% @ush.each do |item|  %>
			<tr class="center aligned">
				<td><%= item.id %></td>
				<td><%= item.route.origin + " - " + item.route.destination %></td>
				<td><%= item.departure_time %></td>
				<td><%= time_ago_in_words(item.created_at) %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/admin/dashboard/user_search_stats.html.erb
<% provide(:title,"آمار سرچ کاربران") %>
<%= render 'menu' %>

<div class="ui container" style="margin-top: 2em">
	<table class="ui celled striped table ">
		<thead>
			<tr class="center aligned">
				<th><h4>route</h4></th>
				<th><h4>count</h4></th>
				<th><h4>percentage</h4></th>
			</tr>
		</thead>
		<tbody>
			<% @routes_count_hash.each do |item|  %>
			<tr class="center aligned">
				<td><%= item[0] %></td>
				<td><%= item[1] %></td>
				<td><%= (item[1]*100/@user_search_histories_all) %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<table class="ui celled striped table ">
		<thead>
			<tr class="center aligned">
				<th><h4>days to flight</h4></th>
				<th><h4>count</h4></th>
				<th><h4>percentage</h4></th>		  
			</tr>
		</thead>
		<tbody>
			<% @dates_count.each do |item|  %>
			<tr class="center aligned">
				<td><%= item[0] %></td>
				<td><%= item[1] %></td>
				<td><%= (item[1]*100/@user_search_histories_all) %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/admin/dashboard/users.html.erb
<% provide(:title,"کاربران") %>
<%= render 'menu' %>

<div class="ui container" style="margin-top: 2em">

	<h4 class="ui horizontal divider header">
	Users
	</h4>
	<div class="ui statistics">
		<div class=" statistic">
			<div class="value">
				<%= User.count %>
			</div>
			<div class="label">
				Total user
			</div>
		</div>
		<div class="grey statistic">
			<div class="value">
				<%= User.where(channel: "telegram").count %>
			</div>
			<div class="label">
			telegram 
			</div>
		</div>
		<div class="grey statistic">
			<div class="value">
				<%= User.where(channel: "website").count %>
			</div>
			<div class="label">
				website 
			</div>
		</div>
		<div class="yellow statistic">
			<div class="value">
				<%= User.where(channel: "website").where("created_at > ?", tehran_time(Date.today)).count %>
			</div>
			<div class="label">
				Today website 
			</div>
		</div>
		<div class="yellow statistic">
			<div class="value">
				<%= User.where(channel: "telegram").where("created_at > ?", tehran_time(Date.today)).count %>
			</div>
			<div class="label">
				Today Telegram 
			</div>
		</div>
	</div>

	<h4 class="ui horizontal divider header">
	Details
	</h4>

	<a href="?channel=telegram">
		<div class="ui blue horizontal label">
			telegram
		</div>
	</a>

	<a href="<%= admin_users_path %>">
		<div class="ui black horizontal label">
			all
		</div>
	</a>

	<table class="ui celled striped table ">
		<thead>
			<tr class="center aligned">
				<th><h4>Id</h4></th>
				<th><h4>Email</h4></th>
				<th><h4>Name</h4></th>
				<th><h4>Channel</h4></th>
				<th><h4>Created at</h4></th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user|  %>
			<tr class="center aligned">
				<td>
					<a href="<%= admin_show_user_path(user.id) %>">
						<%= user.id %>
					</a>
				</td>
				<td><%= user.email %></td>
				<td><%= user.first_name %> <%= user.last_name %></td>
				<td><%= user.channel %></td>
				<td><%= (user.created_at) %></td>
			</tr>
			<% end %>
		</tbody>
</table>
</div>