config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	require 'sidekiq/web'
	require 'sidekiq-scheduler/web'
	
	resources :routes

	namespace :admin do
	  get 'dashboard', to:'dashboard#index', as: 'dashboard'
	  get 'dashboard/weekly_stats', to:'dashboard#weekly_stats', as: 'weekly_stats'
	  get 'dashboard/user_search_histories', as: 'user_search_histories'
	  get 'dashboard/user_search_stats', as: 'user_search_stats'
	  get 'dashboard/search_histories', as: 'search_histories'
	  get 'dashboard/suppliers', as: 'suppliers'
	  get 'dashboard/redirects', as: 'redirects'	
	  get 'dashboard/reviews', as: 'reviews'
	  get 'dashboard/users', as: 'users'
	  get 'dashboard/users/:id', to:'dashboard#show_user', as: 'show_user'
	  post 'dashboard/suppliers', to:'dashboard#update_supplier'
	  post 'dashboard/reviews', to: 'dashboard#update_review', as: 'update_review'
	  delete 'dashboard/reviews', to: 'dashboard#delete_review', as: 'delete_review'
	  mount Sidekiq::Web => '/sidekiq'
	end

	namespace :en do
	  get '/', to:'home#index', as: 'home'
	  get '/flights/', to: 'route#flight', as: 'flight_page'
	  get '/flight_search', to:'search_result#flight_search', as: 'flight_search'
	  get '/flights/:origin_name-:destination_name/:date', to:'search_result#search', as: 'flight_result'
	  get '/flights/:origin_name-:destination_name/:date/:id', to: 'flight_price#index', as: 'flight_prices'
	  get '/flights/:origin_name-:destination_name/', to: 'route#route', as: 'route_page'
	  get 'redirect/:origin_name-:destination_name/:date/:flight_id/:flight_price_id/:channel/:user_id', to: 'redirect#redirect', as: 'redirect'
	end
	
	get 'home/index', as: 'home'
	
	get '/flight_search', to:'search_result#flight_search', as: 'flight_search'
    
	get '/flights/', to: 'route#flight', as: 'flight_page'
	get '/flights/:origin_name-:destination_name-:month/', to: 'route#route', as: 'route_by_month_page'	
	get '/flights/:origin_name-:destination_name/', to: 'route#route', as: 'route_page'
	get '/flights/:origin_name-:destination_name/:date', to:'search_result#search', as: 'flight_result'
	get '/flights/:origin_name-:destination_name/:date/:id', to: 'flight_price#index', as: 'flight_prices'
	
	get 'redirect/:origin_name-:destination_name/:date/:flight_id/:flight_price_id/:channel', to: 'redirect#app_redirect', as: 'app_redirect'
	get 'redirect/:origin_name-:destination_name/:date/:flight_id/:flight_price_id/:channel/:user_id', to: 'redirect#redirect', as: 'redirect'

	post 'notification/price_alert_register', to: 'notification#price_alert_register', as: 'price_alert_register'
	
	get '/us', to:'static_pages#us', as: "us"
	get '/our-service', to:'static_pages#our_service', as: 'our_service'
	get '/policy', to:'static_pages#policy', as: 'policy'

	get '/airline-review/', to: 'review#airline_index', as: 'airline_review_index_page'	
	get '/airline-review/:property_name', to: 'review#airline_reviews', as: 'airline_review_page'
	get '/supplier-review/', to: 'review#supplier_index', as: 'supplier_review_index_page'	
	get '/supplier-review/:property_name', to: 'review#supplier_reviews', as: 'supplier_review_page'
	post '/review', to: 'review#register', as: 'register_review'

	get '/api/v1/city_prefetch_suggestion', to: 'api#city_prefetch_suggestion', as: 'api_city_prefetch_suggestion'
	get '/api/v1/city_suggestion/:query', to: 'api#city_suggestion', as: 'api_city_suggestion'
	get '/api/v1/service-test/', to: 'api#service_test', as: 'service_test'
	get '/api/v1/flights/', to: 'api#flights', as: 'api_flights'
	get '/api/v1/suppliers/', to: 'api#suppliers', as: 'api_suppliers'

	get '/flight-prices/:id', to: redirect('/', status: 301) #, to: 'search_result#flight_prices', as: 'flight-prices-ajax' #, :defaults => { :format => 'js' }
	get '/review/', to: redirect('/airline-review/', status: 301)
	get '/review/:property_name', to: redirect('/airline-review/%{property_name}', status: 301)


	root 'home#index'
end

app/controllers/en/search_result_controller.rb
class En::SearchResultController < SearchResultController
  layout "en/layouts/application"

  private
  def date_to_human date
    date = date.to_date
    if date == Date.today
      "Today"
    elsif date == (Date.today+1) 
      "Tomorrow"
    else
      date.to_date.strftime ' %-d %B' 
    end
  end
      
end

app/controllers/search_result_controller.rb
class SearchResultController < ApplicationController
  
  def flight_search
    origin = params[:search][:origin].downcase
    destination = params[:search][:destination].downcase
    date = params[:search][:date]

    redirect_to  action: 'search', origin_name: origin, destination_name: destination, date: date
  end

  def search 
    origin_name = params[:origin_name].downcase
    destination_name = params[:destination_name].downcase
    date = date_to_code params[:date]
    channel = "website"
    route = Route.new.get_route_by_english_name(origin_name,destination_name)
    user = get_current_user(channel, request.user_agent) 

    if date < Date.today.to_s 
        redirect_to  action: 'search', origin_name: origin_name, destination_name: destination_name, date: "today"
        return
    end

    if route.nil? 
        notfound
    else 
        flights = get_flight_results({route:route, date: date, channel:"website", user_agent_request: request.user_agent, user: user})
        index(route,date,flights)
    end
  end

  def get_flight_results args
    #args = {route,date,channel,user_agent_request,user}
    if is_bot(args[:user_agent_request])
      # do not search supplier, just get results from db
      flights = get_flights(args[:date], args[:route],true)
    else
      search_background_archive args
      flights = get_flights(args[:date],args[:route],false)
    end
    return flights
  end

  def notfound
    render :notfound
  end

  def index(route,date,flights)
    @flights = flights
    origin = City.find_by(city_code: route.origin)
    destination = City.find_by(city_code: route.destination)
    date_in_human = date_to_human date    
    @search_parameter ={origin_english_name: origin.english_name, origin_persian_name: origin.persian_name, origin_code: origin.city_code,
                            destination_english_name: destination.english_name, destination_persian_name: destination.persian_name, destination_code: destination.city_code,
                            date: date, date_in_human: date_in_human, international: route.international}
    @route_days = RouteDay.week_days(origin.city_code,destination.city_code)
        
    if date <= Date.today.to_s
      @flight_dates = Flight.new.get_lowest_price_timetable(origin.city_code,destination.city_code,Date.today.to_s)
    else
      @flight_dates = Flight.new.get_lowest_price_timetable(origin.city_code,destination.city_code,date)
    end   
    @is_mobile = browser.device.mobile?    
    @prices = Flight.new.get_lowest_price_for_a_month(origin.city_code, destination.city_code, Date.today)

    render :index
  end

 
  private

  def search_background_archive args
    if Rails.env.production?
      UserSearchHistoryWorker.perform_async(args[:route].id,args[:date],args[:channel],args[:user].id)
      AmplitudeWorker.perform_async(args[:user].id,"search",args[:channel])
    else
      UserSearchHistory.create(route_id: args[:route].id, departure_time: args[:date], channel: args[:channel], user: args[:user])
    end
  end

  def get_flights(date,route,is_bot)
    if is_bot
        FlightResult.new(route,date).get_archive
    else
        date >= Date.today.to_s ? FlightResult.new(route,date).get : Array.new
    end
  end

  def date_to_human date
    date = date.to_date
    if date == Date.today
      "امروز"
    elsif date == (Date.today+1) 
      "فردا"
    else
      date.to_date.to_parsi.strftime ' %-d %B' 
    end
  end

  def date_to_code date
    if date == "today"
      date = Date.today.to_s
    elsif date == "tomorrow"
      date = (Date.today+1).to_s
    else
      date = date
    end
  end

  def get_current_user(channel, user_agent_request) 
    user = automatic_login({channel: channel, user_agent_request: user_agent_request})
  end

      
end

app/helpers/en/search_result_helper.rb
module En::SearchResultHelper
	
	def en_delay_to_human delay
		unless delay.nil?
			return "<i class=\"warning circle yellow icon\"></i>  #{delay}m delay".html_safe
		end
	end

	def en_trip_duration_to_human total_minute
		message = " "
		unless total_minute.nil?
			message = " "
			hours = total_minute / 60
			minutes = (total_minute) % 60
			message = "#{hours} hours " unless hours == 0 
			message += "and #{minutes} minutes " unless minutes == 0 
		end
		return message
	end

	def en_stop_to_human stops
		if stops.nil?
			message = "Non-stop" 
		else
			stops = stops.split(",")
			message = "#{stops.count} stop at "
		  stops.each_with_index do |stop, index|
				message += " and " if index >= 1
				message += stop
			end
		end
		message
	end

	def number_with_zero(number)
	  number_string = number.to_s
	  case number_string.size
	  when 5
		number_with_zero = "000" + number_string
	  when 6
		number_with_zero = "00" + number_string
	  when 7
		number_with_zero = "0" + number_string
	  when 8
		number_with_zero = number_string	
	  end
	  number_with_zero
	end

	def en_day_name date,saerch_parameter_date
		date = date.to_date
		day_name = nil
		if date == Date.today 
			day_name = "today"
		elsif date == (Date.today+1) 
			day_name = "tomorrow"
		else
			day_name = date.strftime("%A")
		end
		(search_date_identifier(date,saerch_parameter_date)+day_name).html_safe
	end

	def en_price_to_human price
		if price.nil? 
			message = "<i class='plane icon'></i>".html_safe 
		else
			 message = ("$"+price.to_s ).html_safe
		end
		message
	end

	def en_hour_to_human (time)
		time_without_colon  = "#{time}".tr(':', '')
		phrase = case time_without_colon.to_i
        	when 400..1159 then "morning"
        	when 1200..1559 then "noon"
        	when 1600..1959 then "evening"
        	when 2000..2359 then "night"
        	when 0..359 then "night"
        else
        	" "
       	end
       	time + " " + phrase
	end

	def en_airplane_name_for airplane_type
	  case airplane_type.upcase
	  when "MD80","M82","MD-80","MD82","MD-82","MD83","MD-83","MD88","MD-88","MD.88","BOEING MD","MS"
	  	ariplane_name = "Boeing MD"
	  when "AB3"
	  	ariplane_name = "Airbus"
	  when "A300-600"
	  	ariplane_name= "Airbus 300"
	  when "A310","AIRBUS A310"
		  ariplane_name = "Airbus 310"
	  when "A313","AIRBUS A313"
			ariplane_name = "Airbus 313"
	  when "A319","AIRBUS A319"
			ariplane_name = "Airbus 319"
	  when "A321","AIRBUS A321", "AIRBUS 321"
			ariplane_name = "Airbus 321"
	  when "A320","AIRBUS A320","320","AIRBUS 320"
	  	ariplane_name = "Airbus 320"
	  when "BOEING 727-200","727","727-200","B727","B.727","BOEING 727"
	  	ariplane_name = "Boeing 727"
	  when "B737","737","737-500","B737-400","737-300","737-600","737-300","737-700","737-100","BOEING 737"
	  	ariplane_name = "Boeing 737"
	  when "FOKKER 100","F100", "100","FOKER"
	  	ariplane_name = "Fokker 100"
	  when "747"
	  	ariplane_name = "Boeing 747"		
	  end
	  
	  ariplane_name ||= airplane_type
	end

end

app/helpers/search_result_helper.rb
module SearchResultHelper
	
	def delay_to_human delay
		unless delay.nil?
			return "<i class=\"warning circle yellow icon\"></i>احتمال  #{delay} دقیقه تاخیر".html_safe
		end
	end

	def trip_duration_to_human total_minute
		message = " "
		unless total_minute.nil?
			message = " "
			hours = total_minute / 60
			minutes = (total_minute) % 60
			message = "#{hours} ساعت " unless hours == 0 
			message += "و #{minutes} دقیقه " unless minutes == 0 
		end
		return message
	end

	def stop_to_human stops
		if stops.nil?
			message = "بدون توقف" 
		else
			stops = stops.split(",")
			message = "#{stops.count} توقف در "
		  stops.each_with_index do |stop, index|
				message += " و " if index >= 1
				message += stop
			end
		end
		message
	end

	def number_with_zero(number)
	  number_string = number.to_s
	  case number_string.size
	  when 5
		number_with_zero = "000" + number_string
	  when 6
		number_with_zero = "00" + number_string
	  when 7
		number_with_zero = "0" + number_string
	  when 8
		number_with_zero = number_string	
	  end
	  number_with_zero
	end

	def day_name date,saerch_parameter_date
		date = date.to_date
		day_name = nil
		if date == Date.today 
			day_name = "امروز"
		elsif date == (Date.today+1) 
			day_name = "فردا"
		else
			day_name = date.to_parsi.strftime("%A")
		end
		(search_date_identifier(date,saerch_parameter_date)+day_name).html_safe
	end

	def search_date_identifier date,saerch_parameter_date
		if saerch_parameter_date.to_date == date.to_date
			"<i class='arrow down icon'></i>" 
		else
			""
		end
	end

	def price_to_human price
		if price.nil? 
			message = "<i class='plane icon'></i>".html_safe 
		else
			 #number_with_delimiter(price)
			 message = ((price/1000).to_s + "<sup><span style='font-size:0.5em'>هزارتومان</span></sup>").html_safe
		end
		message
	end

end

app/views/search_result/index.html.erb
<%= render 'layouts/header' %>
<% provide(:canonical,"<link rel=\"canonical\" href=\"http://parvazhub.com/flights/#{@search_parameter[:origin_english_name]}-#{@search_parameter[:destination_english_name]}\"/> ".html_safe)%>

<% provide(:title,"بلیط  #{@search_parameter[:destination_persian_name]} | پرواز #{@search_parameter[:origin_persian_name]} #{@search_parameter[:destination_persian_name]} #{@search_parameter[:date_in_human]} | پروازهاب")%>
<% provide(:description,"لیست ارزان‌ترین قیمت‌های بلیط #{@search_parameter[:destination_persian_name]}. تمام پروازهای چارتری و سیستمی پرواز #{@search_parameter[:origin_persian_name]} به #{@search_parameter[:destination_persian_name]}  #{@search_parameter[:date_in_human]} سایت‌های معتبر را در پروازهاب ببینید") %>

<div class="ui container" id="search-results-container">
	<div class="ui grid" id="results-message">
  		<div class="one column row">
    		<div class="column">
				<div class="results-header">
					<i class="plane icon"></i> 
					<%= @search_parameter[:origin_persian_name] %>
				  	به	 
				 	<%= @search_parameter[:destination_persian_name] %> 
					 <%= @search_parameter[:date].to_date.to_parsi.strftime "%A %-d %B"   %>
					   
					<a class="light-yellow ui primary basic blue" onclick="$('#search-box-inner').transition('slide');" style="cursor:pointer; padding-left:5px; font-size:0.8em;">
						<i class="yellow chevron down icon"></i> تغییر شهر/تاریخ
					</a>
				</div>
				<div style="font-size:0.8em">
					<a class="light-yellow" href="<%= route_page_path(@search_parameter[:origin_english_name],@search_parameter[:destination_english_name]) %>">
						<i class="yellow line chart icon"></i> مقایسه قیمت در تمام ماه
					</a>
					     
					<a style="margin-right:12px;"class="light-yellow" href="<%= flight_result_path(@search_parameter[:destination_english_name], @search_parameter[:origin_english_name],@search_parameter[:date]) %>">
						<i class="yellow sync icon"></i> مشاهده پروازهای برگشت
					</a>
				</div>

		 	</div>
		</div> 	
	</div>

	<div class="ui" id="search-box-inner">
		<%= form_for(:search, url: flight_search_path, method: :get, html: {id:"flight_search"}) do |f| %>
			<div class="ui form">
				<div class="four fields">
					<div class="field input-container">
						<label class="search-label">از</label>
						<%= f.text_field :originـfield,{:class =>'origin-field typeahead dir-rtl web-font',placeholder: "مبدا (شهر فارسی یا انگلیسی)", value:@search_parameter[:origin_persian_name]} %>			
						<%= f.hidden_field :origin,{:id =>'origin',value:@search_parameter[:origin_english_name]} %>
					</div>
					<div class="field input-container">
						<label class="search-label">به</label>
						<%= f.text_field :destination_field,{:class =>'destination-field typeahead dir-rtl web-font',placeholder: "مقصد (شهر فارسی یا انگلیسی)",value:@search_parameter[:destination_persian_name]} %>
						<%= f.hidden_field :destination,{:id =>'destination',value:@search_parameter[:destination_english_name]} %>
					</div>
					<div class="field ui calendar">
						<div class="ui input left icon">
							<i class="calendar icon"></i>
							<%= f.text_field :date_shamsi, {id: 'date-picker', class:'form-control web-font', value: @search_parameter[:date], readonly: 'readonly', autocomplete: 'off'} %>
							<%= f.text_field :date, {id: 'date-picker-field'} %>
						</div>
					</div>
					<div class="field center aligned">
						<%= f.submit "جستجوی مجدد", class: "ui submit web-font yellow button  fluid waiting-modal" %>
					</div>
				</div>
			</div>
		<%end%>
	</div>

	<div class="ui mini five statistics" id="flight-price-table" >
	  <% @flight_dates.each do |flight_date|%>
	  	<div class=" grey statistic">
		  <div class="valuee">
			  <%= link_to(price_to_human(flight_date[:price]), search_link_builder(@search_parameter[:origin_english_name],@search_parameter[:destination_english_name],flight_date[:date]))   %> 
		  </div>
		  <div class="label statistic-label  web-font">
		  	<%= link_to(day_name(flight_date[:date],@search_parameter[:date]), search_link_builder(@search_parameter[:origin_english_name],@search_parameter[:destination_english_name],flight_date[:date]))   %>
		  </div>
	   	</div>
	  <% end %>
	</div>

	<% unless @flights.empty? %>
	<table class="ui blue table unstackable sortable rtl" id="flight-prices">
	  	<thead>
			<tr class="center aligned web-font">
	  			<th class="table-header">ایرلاین</th>
	  			<th class="table-header">ساعت </th>
	  			<th class="table-header nm">هواپیما</th>
	  			<th class="table-header sorted ascending">قیمت</th>
	  		</tr>
	  	</thead>
		<tbody>
			<% @flights.each do |flight|  %>
				<% unless ((flight[:best_price] == 0) or (flight[:supplier_count] == 0))  %>
					<tr class="center aligned very basic" >
						<td class="left aligned">
							<div class="two fields">
								<div class="field">
									<a href="<%= flight_prices_path(@search_parameter[:origin_english_name],@search_parameter[:destination_english_name],@search_parameter[:date],flight[:id]) %>" data-remote="false">														
										<h5 class="ui image header web-font">
											<%= airline_logo_for flight[:airline_code] %> 
											<span class="content" style="font-size:0.9em">
												<%= flight[:airline_persian_name].nil? ? flight[:airline_english_name] : flight[:airline_persian_name] %>
												<span class="ui tiny rating">
											    </span>
												<span class="sub header" style="margin-top: 7px">
													<span class="nm"><%= flight[:flight_number].split(",").first %></span>
													<span class="mobile-only"><%= flight[:airplane_type].blank? ? "" : airplane_name_for(flight[:airplane_type]) %></span>													
												</span>
											</span>
										</h5>
									</a>
								</div>
								<div class="field">
									<div class="mini ui basic  web-font rate-button dir-rtl text-right" data-content="امتیاز کاربران به <%= flight[:airline_persian_name] %>. برای ثبت کلیک کنید" >
										<a href="<%= airline_review_page_path(flight[:airline_english_name]) %>" >
											<%= get_star_icon(5,flight[:airline_rate_average],"green","small").html_safe %>
										</a>
									</div>	
								</div>
							</div>
							<% if @search_parameter[:international] %>
								<div style="font-size: 0.8em;color: #797777;">
									<i class="ticket icon"></i>
									<%= stop_to_human flight[:stops]  %>
								</div>
							<% end %>	
						</td>
						<td>
							<div class="content" style="font-size: 0.9em;color: #1d1c1c;">
								<i class="plane grey icon"></i>	
								<%= hour_to_human flight[:departure_time].to_datetime.strftime("%H:%M") %>  
								<% unless flight[:arrival_date_time].nil? %>
									<div style="width:100%; margin-top:5px;border-top: 1px dashed #eee;padding-top:6px;">
										<i class="vertically flipped plane  grey icon"></i>
										<%= hour_to_human flight[:arrival_date_time].to_datetime.strftime("%H:%M")  %>
									</div>
								<% end %>
				            	<div class="sub header" style="margin-top: 7px;color: gray;font-size: 0.8em;">
									<%= (delay_to_human flight[:delay]) %>
				          		</div>
							</div>
							<% if @search_parameter[:international] %>
							<div style="font-size: 0.8em;color: #797777;">
								<i class="wait icon"></i>
								کل زمان سفر <%= trip_duration_to_human flight[:trip_duration] %>
							</div>
						<% end %>	
						</td>
						<td class="nm">
							<%= flight[:airplane_type].blank? ? "-" : airplane_name_for(flight[:airplane_type]) %>
							
							
						</td>
						<td>
							<div class="hide">
								<%= number_with_zero(flight[:best_price]) %>
							</div>
							<a href="<%= flight_prices_path(@search_parameter[:origin_english_name],@search_parameter[:destination_english_name],@search_parameter[:date],flight[:id]) %>" data-remote="false">	
								<button class="ui submit yellow web-font fluid right labeled icon button flight-price-button" style="padding-right: 0 !important;">
									<i class="right arrow icon"></i> از	
									<span class="white"><%= "#{number_with_delimiter(flight[:best_price])} تومان " %></span>
								</button>
							</a>
							
							<div class="suppliers-count">	
								<a href="<%= flight_prices_path(@search_parameter[:origin_english_name],@search_parameter[:destination_english_name],@search_parameter[:date],flight[:id]) %>" data-remote="false" style="color:black">	
									 ارزان‌ترین قیمت بلیط از <b><%= flight[:supplier_count] %></b> سایت 
								</a>
							</div>
						</td>
					</tr>
					
				<% end %>	
			<% end %>
		</tbody>
	</table>
	<% end %>

	<% if @flights.empty? %>
	  	<div class="standard-text" style="background:white;padding-top:2em;margin:2em;direction:rtl">
		
			<i class="blue info circle  icon big"></i>	
			<% if @search_parameter[:date].to_date < Date.today %>
				امروز 
				<%= Date.today.to_date.to_parsi.strftime "%A %-d %B"   %> 
				است. تاریخ پرواز را از لینک‌های پایین انتخاب کنید:
			<% else %>
			پروازی در روز 
			<%= @search_parameter[:date].to_date.to_parsi.strftime "%A %-d %B"   %> 
			موجود نیست. و یا ظرفیت پرواز پر شده است.
			پرواز برای تاریخ‌های زیر را چک کنید:	
			<% end %>
			
			<ul>
				<% @flight_dates.each do |flight_date|%>
					<% unless flight_date[:date] == @search_parameter[:date].to_s %>
					
					<li>
						<% link_text = "جستجوی پرواز #{@search_parameter[:origin_persian_name]} به #{@search_parameter[:destination_persian_name]} "+flight_date[:date].to_date.to_parsi.strftime("%A %-d %B ") %>
						<%= link_to(link_text, search_link_builder(@search_parameter[:origin_english_name],@search_parameter[:destination_english_name],flight_date[:date]))   %>
					</li>
					<% end %>
				<% end %>
			</ul>
			اگر همچنان موفق به پیدا کردن پرواز مورد نظرتان نشدید، صفحه‌ی  
			<%= link_to "پروازهای #{@search_parameter[:origin_persian_name]} به #{@search_parameter[:destination_persian_name]}", route_page_path(origin_name:  @search_parameter[:origin_english_name],destination_name: @search_parameter[:destination_english_name], :anchor => "city-calendar"),class:"city-page-link" %> روی تقویم را ببینید.

			<h5 class="web-font">
			<i class="blue info circle  icon big"></i>	
			
				چه روزهایی
				<%= " #{@search_parameter[:origin_persian_name]} به  #{@search_parameter[:destination_persian_name]}" %> 
				پرواز دارد؟
			</h5>
			<% unless @route_days.empty? %>
				<% @route_days.each do |day|   %>
					<%= week_day_to_human_persian day  %>
				<% end %>
			<% else %>
				برای هیچ روزی در هفته پروازی در این مسیر وجود ندارد.
			<% end %>
		
		</div>	
	<% end %>

	<%= render :partial => "route/price_chart", :locals => {prices: @prices, origin: @search_parameter[:origin_persian_name], destination: @search_parameter[:destination_persian_name] } %>

</div>

<div class="ui basic modal prices">
      <p id="prices-modal-content"></p>
</div>
<script>
	$('table').tablesort();
	$('.rate-button').popup();
</script>
<%= render 'layouts/searchbox-helper', date_picker_inline: false %>   
<%= render 'layouts/footer' %>

app/views/search_result/notfound.html.erb
<%= render 'layouts/header' %>
<% provide(:title,"پروازهاب:‌ پروازی موجود نیست")%>

<div class="ui container" id="search-results-container" style="direction: rtl;padding-top: 2em;" >
	<div class="ui stackable one column grid centered" style="margin-top: 1em">
	<div style="font-size:1.5em; padding:1.5em">
	مسیر مورد نظر شما در سیستم ما موجود نیست. لطفا مسیر دیگری انتخاب کنید.
	</div>
	
	<%= form_for(:search, url: flight_search_path, method: :get, html: {id:"flight_search"}) do |f| %>
		<div class="ui huge form" >
			<div class="two fields">
				<div class="field input-container">
					<%= f.text_field :originـfield,{:class =>'origin-field typeahead dir-rtl web-font',placeholder: "از مبدا (شهر یا فرودگاه)"} %>						   
					<%= f.hidden_field :origin,{:id =>'origin'} %>
				</div>
				
				
				<div class="field input-container">
					<%= f.text_field :destination_field,{:class =>'destination-field typeahead dir-rtl web-font',placeholder: "به مقصد (شهر یا فرودگاه)"} %>
					<%= f.hidden_field :destination,{:id =>'destination'} %>
				</div> 
			</div>
			<div id="date-picker" style="height: 10em; font-family: samim;">
					<%= f.text_field :date, {id: 'date-picker-field'} %>
			</div>
			<div class="ui center aligned basic segment" style="margin-top: 50px;">
				<button class="ui submit massive yellow web-font fluid right labeled waiting-modal icon button" type="submit">
						<i class="right arrow icon"></i>
						نمایش پروازها
				</button>
			</div>
		</div>
	<%end%>
	</div>

</div>

<%= render 'layouts/searchbox-helper', date_picker_inline: false %>   