config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	require 'sidekiq/web'
	require 'sidekiq-scheduler/web'
	
	resources :routes

	namespace :admin do
	  get 'dashboard', to:'dashboard#index', as: 'dashboard'
	  get 'dashboard/weekly_stats', to:'dashboard#weekly_stats', as: 'weekly_stats'
	  get 'dashboard/user_search_histories', as: 'user_search_histories'
	  get 'dashboard/user_search_stats', as: 'user_search_stats'
	  get 'dashboard/search_histories', as: 'search_histories'
	  get 'dashboard/suppliers', as: 'suppliers'
	  get 'dashboard/redirects', as: 'redirects'	
	  get 'dashboard/reviews', as: 'reviews'
	  get 'dashboard/users', as: 'users'
	  get 'dashboard/users/:id', to:'dashboard#show_user', as: 'show_user'
	  post 'dashboard/suppliers', to:'dashboard#update_supplier'
	  post 'dashboard/reviews', to: 'dashboard#update_review', as: 'update_review'
	  delete 'dashboard/reviews', to: 'dashboard#delete_review', as: 'delete_review'
	  mount Sidekiq::Web => '/sidekiq'
	end

	namespace :en do
	  get '/', to:'home#index', as: 'home'
	  get '/flights/', to: 'route#flight', as: 'flight_page'
	  get '/flight_search', to:'search_result#flight_search', as: 'flight_search'
	  get '/flights/:origin_name-:destination_name/:date', to:'search_result#search', as: 'flight_result'
	  get '/flights/:origin_name-:destination_name/:date/:id', to: 'flight_price#index', as: 'flight_prices'
	  get '/flights/:origin_name-:destination_name/', to: 'route#route', as: 'route_page'
	  get 'redirect/:origin_name-:destination_name/:date/:flight_id/:flight_price_id/:channel/:user_id', to: 'redirect#redirect', as: 'redirect'
	end
	
	get 'home/index', as: 'home'
	
	get '/flight_search', to:'search_result#flight_search', as: 'flight_search'
    
	get '/flights/', to: 'route#flight', as: 'flight_page'
	get '/flights/:origin_name-:destination_name-:month/', to: 'route#route', as: 'route_by_month_page'	
	get '/flights/:origin_name-:destination_name/', to: 'route#route', as: 'route_page'
	get '/flights/:origin_name-:destination_name/:date', to:'search_result#search', as: 'flight_result'
	get '/flights/:origin_name-:destination_name/:date/:id', to: 'flight_price#index', as: 'flight_prices'
	
	get 'redirect/:origin_name-:destination_name/:date/:flight_id/:flight_price_id/:channel', to: 'redirect#app_redirect', as: 'app_redirect'
	get 'redirect/:origin_name-:destination_name/:date/:flight_id/:flight_price_id/:channel/:user_id', to: 'redirect#redirect', as: 'redirect'

	post 'notification/price_alert_register', to: 'notification#price_alert_register', as: 'price_alert_register'
	
	get '/us', to:'static_pages#us', as: "us"
	get '/our-service', to:'static_pages#our_service', as: 'our_service'
	get '/policy', to:'static_pages#policy', as: 'policy'

	get '/airline-review/', to: 'review#airline_index', as: 'airline_review_index_page'	
	get '/airline-review/:property_name', to: 'review#airline_reviews', as: 'airline_review_page'
	get '/supplier-review/', to: 'review#supplier_index', as: 'supplier_review_index_page'	
	get '/supplier-review/:property_name', to: 'review#supplier_reviews', as: 'supplier_review_page'
	post '/review', to: 'review#register', as: 'register_review'

	get '/api/v1/city_prefetch_suggestion', to: 'api#city_prefetch_suggestion', as: 'api_city_prefetch_suggestion'
	get '/api/v1/city_suggestion/:query', to: 'api#city_suggestion', as: 'api_city_suggestion'
	get '/api/v1/service-test/', to: 'api#service_test', as: 'service_test'
	get '/api/v1/flights/', to: 'api#flights', as: 'api_flights'
	get '/api/v1/suppliers/', to: 'api#suppliers', as: 'api_suppliers'

	get '/flight-prices/:id', to: redirect('/', status: 301) #, to: 'search_result#flight_prices', as: 'flight-prices-ajax' #, :defaults => { :format => 'js' }
	get '/review/', to: redirect('/airline-review/', status: 301)
	get '/review/:property_name', to: redirect('/airline-review/%{property_name}', status: 301)


	root 'home#index'
end

app/models/flight_price.rb
class FlightPrice < ApplicationRecord
	belongs_to :flight, counter_cache: true

	def self.delete_old_flight_prices(supplier,route_id,date)
      flights = Flight.select(:id).where(route_id: route_id).where(departure_time: date.to_datetime.beginning_of_day.to_s..date.to_datetime.end_of_day.to_s).to_a
	  flights = flights.map{ |flight| flight.id}
	  FlightPrice.where(flight_id: flights).where(flight_date:"#{date}").where(supplier: "#{supplier}").delete_all
	end 

	def get(flight_id,result_time_to_live)
	  responses = Array.new
	  suppliers_list = FlightPrice.select(:id, :flight_id, :price, :supplier, :created_at).where(flight_id: flight_id)
				.where('created_at >= ?', result_time_to_live)
				.order(:price)
	  suppliers_list.each do |supplier|
		response = Hash.new
		response[:id] = supplier.id
		response[:flight_id] = supplier.flight_id
		response[:price] = supplier.price
		response[:price_dollar] = to_dollar(supplier.price) 
		response[:supplier_english_name] = supplier.supplier
		response[:created_at] = supplier.created_at
		response[:supplier_persian_name] = supplier_persian_name supplier.supplier
		response[:supplier_logo] = supplier_logo supplier.supplier
		responses << response
	  end
	  return responses
	end

	private
	def supplier_logo supplier_name
	  Supplier.new.get_logo supplier_name
	end

	def supplier_persian_name(supplier_name)
	  Supplier.new.get_persian_name supplier_name
	end

	def to_dollar amount
    Currency.new.to_dollar amount
  end
end

app/controllers/en/flight_price_controller.rb
class En::FlightPriceController < FlightPriceController
  layout "en/layouts/application"
  
end

app/controllers/flight_price_controller.rb
class FlightPriceController < ApplicationController

  def index
    origin_name = params[:origin_name].downcase
    destination_name = params[:destination_name].downcase
    date = params[:date]
    flight_id = params[:id]
    channel = "website"
    @dates, @georgian_dates, @prices = Array.new, Array.new, Array.new

    origin = City.find_by(english_name: origin_name.downcase) 
    destination = City.find_by(english_name: destination_name.downcase)

    date_in_human = date_to_human date #date.to_date.to_parsi.strftime '%A %d %B'   
    @flight = Flight.find(flight_id)
    @user = get_current_user(channel, nil) 
    @search_parameter ={origin_english_name: origin.english_name, origin_persian_name: origin.persian_name, origin_code: origin.city_code,
                        destination_english_name: destination.english_name, destination_persian_name: destination.persian_name, destination_code: destination.city_code,
                        date: date, date_in_human: date_in_human}
    
    @flight_prices = get_flight_price(@flight,channel,request.user_agent, current_user)
    @flight_price_over_time = FlightPriceArchive.flight_price_over_time(flight_id,date)
    @flight_price_over_time.each do |date,price|
        @georgian_dates <<  date.to_s.to_date.strftime("%A %d %B")
        @dates <<  date.to_s.to_date.to_parsi.strftime("%A %d %B")
        @prices << price
    end
    
    @airline = Airline.find_by(code: @flight.airline_code.split(",").first) 
    @reviews = get_reviews @airline
  
    render :index
  end

  def get_flight_price(flight,channel,user_agent_request,user)
    flight_price_background_archive(channel,flight,user)  unless is_bot(user_agent_request)
    FlightResult.new.get_flight_price(flight)
  end

  private

  def flight_price_background_archive channel,flight,user
    if Rails.env.production?
      UserFlightPriceHistoryWorker.perform_async(channel,flight.id,user.id) 
      AmplitudeWorker.perform_async(user.id,"supplierPage",channel)
    else
      UserFlightPriceHistory.create(flight_id: flight.id,channel: channel, user: user)
    end
  end

  def get_reviews airline
    if airline.nil?
      reviews = Array.new
    else
      reviews = Review.where(page: airline.english_name).where.not(text:"")
    end
  end

  def date_to_human date
    date = date.to_date
    if date == Date.today
      "امروز"
    elsif date == (Date.today+1) 
      "فردا"
    else
      date.to_date.to_parsi.strftime ' %-d %B' 
    end
  end

  def get_current_user(channel, user_agent_request) 
    user = automatic_login({channel: channel, user_agent_request: user_agent_request})
  end   
end

app/helpers/en/flight_price_helper.rb
module En::FlightPriceHelper

  def hour_to_human_for_en_title (time)
		time_without_colon  = "#{time}".tr(':', '')
		phrase = case time_without_colon.to_i
        	when 400..1159 then "morning"
        	when 1200..1559 then "noon"
        	when 1600..1959 then "evening"
        	when 2000..2359 then "night"
        	when 0..359 then "night"
        else
        	" "
       	end
       	phrase
	end

	def english_airline_name_for airline
		if airline.nil?
		  name = ""
		else
		  name = airline.english_name.sub("-"," ").humanize
		end
		name
	end

end

app/views/flight_price/_flight_prices.html.erb
	<div style="text-align: right"><i class="close big icon"></i></div>
	<table class="ui teal table rtl" style="width:97% !important">
		<tbody>
			<% @flight_prices.each_with_index do |flight_price,index|  %>
				<tr class="center aligned very basic">
					<td width="1%">
						<% if index==0 %>	
							<span class="ui red tiny label"><i class="checkmark icon"></i>ارزان‌ترین</span>
						<% end %>
					</td>
					<td>	
						<%= supplier_logo_for flight_price.supplier, false %>
						وب‌سایت <%=  flight_price[:supplier_persian_name] %> 
					</td>
					<td>	
						<a href="/redirect/website/<%= flight_price.id%>"  target= "_blank">
							<b><%= number_with_delimiter(flight_price.price) %></b> تومان
						</a>
					</td>
					<td>
						 <a href="/redirect/website/<%= flight_price.id%>" class="ui green label  flight-price"  target= "_blank">
						 	<i class="external icon"></i> خرید از سایت <%=  flight_price[:supplier_persian_name] %>  در پنجره جدید 
						 </a>
						<!--<span style="font-size:x-small"><%=  time_ago_in_words(flight_price.created_at) %> ago</span>-->
					</td>
					<td width="10%">
					</td>
				</tr>
			<% end %>
			<% if @flight_prices.empty?  %>
				<tr class="center aligned very basic">
					<td>
						<p>پروازی که انتخاب کرده‌اید پر شده است.  
						<a href="#" onclick="javascript:window.location.reload(true); ">نمایش لیست به روز شده </a>
						</p>
					</td>
				</tr>
			<% end %>
			<% if @prices.count > 1 %>
				<tr>
					<td colspan="6">
						<div style="width:90%; min-height:10em; margin:auto;" >
							<canvas id="myChart"></canvas>

							<script>
							var labels = <%= raw @dates %>;
							var data = <%= @prices %>;
							var ctx = document.getElementById("myChart").getContext('2d');
							$(document).ready(function(){
								var myChart = new Chart(ctx, {
									type: 'line',
									data: {labels: labels,datasets: [{label: "تغییرات حداقل قیمت بلیط",borderColor: 'rgb(154, 154, 154)',backgroundColor:  'rgb(154, 154, 154)', data: data,fill: false,lineTension: 0}]},
									options: {
										showLines: true,
										scales: {
											xAxes: [{
												ticks: {
													autoSkip: false
												}
											}]
										}
									}
								});
							});
							</script>
						</div>
					</td>
				</tr>
			<% end %>
		</tbody>		
	</table>
	
	<div class="ui cancel button web-font">بازگشت به لیست پروازها</div>

app/views/flight_price/flight_prices.js.erb
$('.ui.basic.modal.prices')
    .modal('setting', 'closable', true)
    .modal('show');
   
$("#prices-modal-content").html("<%= escape_javascript(render partial: 'flight_prices') %>");

$('.ui.basic.modal.prices')
    .modal('attach events', '.ui.cancel.button', 'hide')
    .modal('attach events', '.close.icon', 'hide');

app/views/flight_price/index.html.erb
<%= render 'layouts/header' %>
<% provide(:canonical,"<link rel=\"canonical\" href=\"http://parvazhub.com/flights/#{@search_parameter[:origin_english_name]}-#{@search_parameter[:destination_english_name]}\"/> ".html_safe)%>
<% provide(:title,"بلیط  #{@search_parameter[:destination_persian_name]} | پرواز #{@search_parameter[:origin_persian_name]} #{@search_parameter[:destination_persian_name]} #{@search_parameter[:date_in_human]} #{airline_name_for(@airline)} #{hour_to_human_for_title(@flight.departure_time.to_datetime.strftime('%H:%M'))} | پروازهاب" ) %>
<% provide(:description,"لیست بهترین قیمت‌های بلیط  #{@search_parameter[:origin_persian_name]} به  #{@search_parameter[:destination_persian_name]} #{@search_parameter[:date].to_date.to_parsi.strftime('%d %B')} ایرلاین #{airline_name_for(@airline)} #{hour_to_human(@flight.departure_time.to_datetime.strftime('%H:%M'))}" ) %>

<div class="ui container" id="search-results-container">

    <div class="row flight-price-route">
        <h5 class="ui image header web-font">
            <%= airline_logo_for @flight.airline_code %> 
            <div class="content">
                سایت‌های فروشنده بلیط پرواز   
                <%= hour_to_human @flight.departure_time.to_datetime.strftime("%H:%M") %>            
                <%= @flight.airplane_type.blank? ? " " : airplane_name_for(@flight.airplane_type) %>
                <%= airline_name_for @airline %>
                <div class="sub header" style="margin-top: 7px">
                    <%= @search_parameter[:origin_persian_name] %>
                    به 
                    <%= @search_parameter[:destination_persian_name] %> 
                    <%= @search_parameter[:date].to_date.to_parsi.strftime "%A %d %B"   %>
                </div>
            </div> 
        </h5> 
        <a href="<%= flight_result_path(@search_parameter[:origin_english_name],@search_parameter[:destination_english_name],@search_parameter[:date]) %> ">
            <button class="ui mini right floated button web-font nm  ">
            بازگشت به صفحه قبل 
            </button>
        </a>
    </div>
 
        <table class="ui  table rtl" style="width:97% !important">
            <tbody>
                <% @flight_prices.each_with_index do |flight_price,index|  %>
                    <tr class="center aligned very basic">
                        <td width="1%">
                            <% if index==0 %>	
                                <span class="ui red tiny label"><i class="checkmark icon"></i>ارزان‌ترین</span>
                            <% end %>
                        </td>
                        <td>
                            <a style="color:black" href="<%= redirect_path(@search_parameter[:origin_english_name],@search_parameter[:destination_english_name],@search_parameter[:date],@flight.id,flight_price[:id],'website', user_id:  @user.id) %>"  target= "_blank" rel="nofollow">                    
                                <%= supplier_logo_for flight_price[:supplier_english_name], false %>
                                 <%= flight_price[:supplier_persian_name] %> 
                            </a>
                            <a style="padding-top:6px; display: block;font-size: 0.8em;" href="<%= supplier_review_page_path flight_price[:supplier_english_name]  %>" >
                                <i class=" comments large icon"></i>
                                نظر‌ کاربران 
                                <%= flight_price[:supplier_persian_name] %> 
                            </a>
                        </td>
                        <td>
                            <div class="suppliers-count">	
                                <b><%= number_with_delimiter(flight_price[:price]) %></b> تومان
                            </div>
                        
                            <a href="<%= redirect_path(origin_name: @search_parameter[:origin_english_name],destination_name: @search_parameter[:destination_english_name], date: @search_parameter[:date],flight_id: @flight.id,flight_price_id: flight_price[:id],channel: 'website', user_id: @user.id) %>" class="ui green label  flight-price"  target= "_blank" rel="nofollow">
                                <i class="external icon"></i> خرید از سایت <%= flight_price[:supplier_persian_name] %>  
                            </a>
                            <!--<span style="font-size:x-small"><%=  time_ago_in_words(flight_price[:created_at]) %> ago</span>-->
                        </td>
                        <td width="10%">
                        </td>
                    </tr>
                <% end %>
                <% if @flight_prices.empty?  %>
                    <tr class="center aligned very basic">
                        <td>
                            <p>پروازی که انتخاب کرده‌اید پر شده است.  
                            </p>
                        </td>
                    </tr>
                <% end %>
                <% if @prices.count > 1 %>
                    <tr>
                        <td colspan="6">
                            <div style="width:90%;min-height:100%; margin:auto" >
                                <canvas id="myChart"></canvas>

                                <script>
                                var labels = <%= raw @dates %>;
                                var data = <%= @prices %>;
                                var ctx = document.getElementById("myChart").getContext('2d');
                                $(document).ready(function(){
                                    var myChart = new Chart(ctx, {
                                        type: 'line',
                                        data: {labels: labels,datasets: [{label: " تغییرات حداقل قیمت بلیط <%= hour_to_human @flight.departure_time.to_datetime.strftime('%H:%M') %> <%= airline_name_for @airline %> ",borderColor: 'rgb(54,162,235)',backgroundColor:  'rgb(54,162,235)', data: data,fill: false,lineTension: 0}]},
                                        options: {
                                            showLines: true,
                                            scales: {
                                                xAxes: [{
                                                    ticks: {
                                                        autoSkip: false
                                                    }
                                                }]
                                            }
                                        }
                                    });
                                });
                                </script>
                            </div>
                        </td>
                    </tr>
                <% end %>
            </tbody>		
        </table>

 
        <% unless @airline.nil? %>
            <div style="direction: rtl;width: 97%;line-height: 2em;font-size: 0.9em;margin-bottom: 2em;">
                <h5 style="font-family: samim;padding: 1em 0;">
                    <i class="comments large icon"></i>
                    آخرین نظرهای مسافران
                    <%= airline_name_for @airline  %>
                </h5>
                <% unless @reviews.empty? %>
                    <% @reviews.each do |review| %>
                        <div class="ui grid review-section review-card" id="<%= review.id %>">
                            <div class="column">
                                    <% if (review.author.nil? or review.author == "") %>
                                        ناشناس:
                                    <% else %>
                                        <%= review.author %>:
                                    <% end %> 
                                <%= review.text %>
                            </div>
                        </div>
                    <% end %>
                    <div class="ui grid review-section review-card" style="font-weight: bold;font-size: 1.1em;padding: 2%;">
                        <a href="<%= airline_review_page_path @airline.english_name  %>" >
                            <i class="comment large icon"></i>

                                نظر شما در مورد پروازهای
                                <%= airline_name_for @airline  %>
                                چیست؟
                        </a>
                    </div>
                <% else %>
                    <div class="ui grid review-section review-card"  >
                        <a href="<%= airline_review_page_path(@airline.english_name,:anchor => 'review-register-form')  %>" >
                        هنوز نظری ثبت نشده. اولین نفری باشید که در مورد
                        <%= airline_name_for @airline  %>
                        نظر می‌دهید!
                        </a>
                    </div>
                <% end %>
            </div>
        <% end %>
        
        <a href="<%= flight_result_path(@search_parameter[:origin_english_name],@search_parameter[:destination_english_name],@search_parameter[:date]) %> ">
            <button class="ui button web-font fluid ">
                بازگشت به لیست پروازهای 
                <%= @search_parameter[:origin_persian_name] %>
                به 
                <%= @search_parameter[:destination_persian_name] %> 
                <i class="left arrow icon"></i>
            </button>
        </a>
          
</div>    

<%= render 'layouts/searchbox-helper', date_picker_inline: false %>   
<%= render 'layouts/footer' %>
    